From: byob-notify-noreply@mozilla.com
Subject: Build Your Own Browser: New user registration

Greetings,

This is an automatically generated email from Mozilla's Build Your Own Browser 
(BYOB) application. The orignating account is not monitored, so please direct 
enquires about this email to the BYOB contact page at <?=$contact_URL?>.

Someone (possibly you) has registered an account using this email address with 
the BYOB application. The account's login name is "<?=$login_name?>".  If you 
are that someone, you will need to follow the link below to verify your email 
address and complete the account activation process. We'd also like you to be 
aware of some conditions regarding the use of BYOB, and distribution of the 
browsers it creates.

BYOB generates installer files for a lightly customized version of Firefox that 
can be publicly distributed. These customized versions of Firefox are licensed 
under the Mozilla Public License (MPL), and the installer files and their 
contents are subject to the restrictions outlined in the Mozilla Trademark 
Policy (links to both documents are below), By using BYOB and/or distributing 
the installers generated by BYOB, you understand and agree to this. 

Mozilla Public License
http://www.mozilla.org/MPL/

Mozilla Trademark Policy
http://www.mozilla.org/foundation/trademarks/policy.html

There are a few rules governing distribution of the installers, and breaking 
any of the rules automatically revokes your (or your organization's) 
authorization to distribute them. The rules, which are further outlined in the 
Mozilla Public License and the Mozilla Trademark Policy are: 

- The program installers generated by BYOB and/or their contents may not be modified in any way
- Any installer distributed must be signed with a digital certificate issued by Mozilla
- The installers must be distributed at no cost to the end-user
- The installers must be distributed as-is as a stand-alone file, and may not be incorporated with a meta-installer or pre-installed
- When referring to the product name, the installer must be referred to using the title generated by BYOB to differentiate it from the default release of Firefox.

If you have any questions regarding these conditions, or need clarification on 
any of the items mentioned here, please contact us through the link below. If 
you agree to adhere to these conditions, then you can verify your email using 
the link below and get started with BYOB.

<?= 
url::full('verifyemail', false, array(
    'email_verification_token' => $email_verification_token
)) . "\n"
?>

Please click on the link above to complete the e-mail verification process and 
login to BYOB. If you believe this email was sent in error, please contact us 
through <?=$contact_URL?>.

Welcome aboard, and thanks for registering.

The Mozilla Build Your Own Browser (BYOB) Team
http://buildyourownbrowser.com
