<?php slot::start('preamble') ?>
    <div class="restrictions">
        <h3>Distribution and generation restrictions</h3>
        <p>Mozilla's Build Your Own Browser (BYOB) application generates installer files for a lightly customized version of Firefox that can be publicly distributed. These customized versions of Firefox are licensed under the <a target="_new" href="http://www.mozilla.org/MPL/">Mozilla Public License</a> (MPL), and the installer files and their contents are subject to the restrictions outlined in the <a target="_new" href="http://www.mozilla.org/foundation/trademarks/policy.html" alt="Mozilla Trademark Policy">Mozilla Trademark Policy</a>. By using BYOB and/or distributing the installers generated by BYOB, you understand and agree to this.</p>

        <p>There are a few rules regarding distribution of the installers, and breaking any of the rules automatically revokes your (or your organization's) authorization to distribute them. The rules, which are further outlined in the Mozilla Public License and the Mozilla Trademark Policy are:</p>

        <ul>
            <li>The program installers generated by BYOB and/or their contents may not be modified in any way</li>
            <li>Any installer distributed must be signed with a digital certificate issued by Mozilla</li>
            <li>The installers must be distributed at no cost to the end-user</li>
            <li>The installers must be distributed as-is as a stand-alone file, and may not be incorporated with a meta-installer or pre-installed</li>
            <li>When referring to the product name, the installer must be referred to as <?=$repack->title?> to differentiate it from the default release of Firefox.</li>
        </ul>

        <p>If you have any questions regarding these conditions, or need clarification on any of the items mentioned here, please <a href="<?=url::base()?>contact">contact us</a>.</p>

    </div>
<?php slot::end() ?>
<?=View::factory('repacks/elements/confirm', array(
    'repack'     => $repack,
    'head_title' => 'release',
    'crumbs'     => 'request release',
    'message'    => 'Request a new release for this browser?',
    'url'        => url::base() . url::current(),
))->render()?>
